/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import dominio.Empleado;
import dominio.Rol;
import gestores.GestorEmpleado;
import gestores.GestorRol;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alumno
 */
public class FrmNuevoEmpleado extends javax.swing.JInternalFrame {

    private GestorEmpleado gestor;
    private Empleado empleado;
    private ArrayList<Rol> roles = new ArrayList<>();
    ArrayList <Empleado> empleados = new ArrayList<>();
    

    /**
     * Creates new form FrmNuevoEmpleado
     * @param gestor
     */
    public FrmNuevoEmpleado(GestorEmpleado gestor) { //Constructor de NUEVO
        initComponents();
        this.gestor = gestor ; 
        for (Rol r: gestor.getRoles()){
            jComboRol.addItem(r); 
        }
        
        
        
        /*Rol rolEmpleado = new Rol();
        rolEmpleado.setNombreRol("Empleado");
        rolEmpleado.setFactorSueldo(1);
        roles.add(rolEmpleado);
        
        Rol rolJefe = new Rol();
        rolJefe.setNombreRol("Jefe");
        rolJefe.setFactorSueldo(1.5);
        roles.add(rolJefe);
        
        this.jComboRol.addItem(rolEmpleado);
        this.jComboRol.addItem(rolJefe);
        this.gestor = gestor;
    */
    }

    public FrmNuevoEmpleado(GestorEmpleado gestor, Empleado empleado) {
        this(gestor);        
        this.empleado = empleado;
        this.txtApellido.setText(this.empleado.getApellido());
        this.txtNombre.setText(this.empleado.getNombre());
        this.jComboRol.setSelectedItem(this.empleado.getRol());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        bntCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboRol = new javax.swing.JComboBox<>();

        jLabel1.setText("Nombre:");

        jLabel2.setText("Apellido:");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        bntCancelar.setText("Cancelar");
        bntCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCancelarActionPerformed(evt);
            }
        });

        jLabel4.setText("Rol");

        jComboRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboRolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombre)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(35, 35, 35)
                        .addComponent(jComboRol, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bntCancelar)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtApellido, txtNombre});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jComboRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntCancelar)
                    .addComponent(btnAceptar))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String apellido = this.txtApellido.getText();
        String nombre = this.txtNombre.getText();
                   
        if (apellido != null && apellido.length() > 0) {
            if (nombre != null && nombre.length() > 0) {
                if (this.empleado == null) {
                    Rol rol = (Rol) jComboRol.getSelectedItem();
                    Empleado nuevoEmpleado = new Empleado(apellido, this.txtNombre.getText(), rol);
                    this.gestor.guardarNuevoEmpleado(nuevoEmpleado);
                        } else { // EDITAR
                            Rol rol = (Rol) jComboRol.getSelectedItem();
                            this.empleado.setApellido(txtApellido.getText());
                            this.empleado.setNombre(txtNombre.getText());
                            this.empleado.setRol(rol);    
                            this.gestor.editarEmpleado(this.empleado);               
                            txtNombre.setText("");                          
                            jComboRol.setSelectedIndex(0);
                            txtApellido.setText("");
                            this.dispose();
                        }
                    }    else {
                JOptionPane.showMessageDialog(this, "Ingrese todos los datos requeridos", "Atención", JOptionPane.ERROR_MESSAGE);
            }
            this.dispose(); 
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese todos los datos requeridos", "Atención", JOptionPane.ERROR_MESSAGE);
        } 
    
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void bntCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCancelarActionPerformed
        
        setVisible(false);
        
    }//GEN-LAST:event_bntCancelarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
             
       
    }//GEN-LAST:event_txtNombreActionPerformed

    private void jComboRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboRolActionPerformed
        // TODO add your handling code here:
        
            
        
       
    }//GEN-LAST:event_jComboRolActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
        
        char c = evt.getKeyChar(); 
        if(Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
        // TODO add your handling code here:
        
        
        char c = evt.getKeyChar(); 
        if(Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtApellidoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCancelar;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JComboBox<Rol> jComboRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

}
