package Modelo;
// Generated 05/11/2019 00:34:25 by Hibernate Tools 4.3.1



import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Modelo generated by hbm2java
 */
@Entity
@Table (name="modelo")
public class Modelo  implements java.io.Serializable {

    @Id @GeneratedValue(strategy=javax.persistence.GenerationType.AUTO) 
    private Long id;
    
    @OneToOne (targetEntity = Marca.class, cascade=CascadeType.DETACH,fetch=FetchType.LAZY)
    private Marca marca;
    private String nombre;
    

    public Modelo() {
    }

	
    public Modelo(Marca marca, String nombre) {
        this.marca = marca;
        this.nombre = nombre;
    }
    public Modelo(Marca marca, String nombre, Set versions, Set vehiculos) {
       this.marca = marca;
       this.nombre = nombre;
       
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Marca getMarca() {
        return this.marca;
    }
    
    public void setMarca(Marca marca) {
        this.marca = marca;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Override
    public String toString() {
        return nombre; //To change body of generated methods, choose Tools | Templates.
    }
}


