package Modelo;
// Generated 05/11/2019 00:34:25 by Hibernate Tools 4.3.1



import java.util.Set;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Motor generated by hbm2java
 */
@Entity
@Table (name="motor")
public class Motor  implements java.io.Serializable {

    @Id @GeneratedValue(strategy=javax.persistence.GenerationType.AUTO)
    private Long id;
    private double motor;
    private int potencia;
    

    public Motor() {
    }

	
    public Motor(double motor, int potencia) {
        this.motor = motor;
        this.potencia = potencia;
    }
    public Motor(double motor, int potencia, Set vehiculos) {
       this.motor = motor;
       this.potencia = potencia;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public double getMotor() {
        return motor;
    }

    public void setMotor(double motor) {
        this.motor = motor;
    }

    public int getPotencia() {
        return potencia;
    }

    public void setPotencia(int potencia) {
        this.potencia = potencia;
    }
    
    
    
    
    @Override
    public String toString() {
        return motor + " + " + potencia + " hp" ; //To change body of generated methods, choose Tools | Templates.
    }



}


