package Modelo;
// Generated 05/11/2019 00:34:25 by Hibernate Tools 4.3.1

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;




/**
 * Vehiculo generated by hbm2java
 */
@Entity
@Table (name="vehiculo")
public class Vehiculo  implements java.io.Serializable {

    @Id @GeneratedValue(strategy=javax.persistence.GenerationType.AUTO)
    private Long id;
    
    @OneToOne (targetEntity = Color.class, cascade= CascadeType.DETACH,fetch=FetchType.LAZY)
    private Color color;
    
    @OneToOne (targetEntity = Condicion.class, cascade= CascadeType.DETACH,fetch=FetchType.LAZY)
    private Condicion condicion;
    
    @OneToOne (targetEntity = Marca.class, cascade= CascadeType.DETACH,fetch=FetchType.LAZY)
    private Marca marca;
    
    @OneToOne (targetEntity = Modelo.class, cascade= CascadeType.DETACH,fetch=FetchType.LAZY)
    private Modelo modelo;
    
    @OneToOne (targetEntity = Motor.class, cascade= CascadeType.DETACH,fetch=FetchType.LAZY)
    private Motor motor;
    
    @OneToOne (targetEntity = Tipocombustible.class, cascade= CascadeType.DETACH,fetch=FetchType.LAZY)
    private Tipocombustible tipocombustible;
    
    @OneToOne (targetEntity = Tipovehiculo.class, cascade= CascadeType.DETACH,fetch=FetchType.LAZY)
    private Tipovehiculo tipovehiculo;
    
    @OneToOne (targetEntity = Version.class, cascade= CascadeType.DETACH,fetch=FetchType.LAZY)
    private Version version;
    private String descripcion;
    private double precioLista;
    private int stock;
    private int kms;

    public Vehiculo() {
    }

	
    public Vehiculo(Color color, Condicion condicion, Marca marca, Modelo modelo, Tipovehiculo tipovehiculo, Version version_1, String descripcion, double precioLista, int stock, int kms) {
        this.color = color;
        this.condicion = condicion;
        this.marca = marca;
        this.modelo = modelo;
        this.tipovehiculo = tipovehiculo;
        this.version = version_1;
        this.descripcion = descripcion;
        this.precioLista = precioLista;
        this.stock = stock;
        this.kms = kms;
    }
    public Vehiculo(Color color, Condicion condicion, Marca marca, Modelo modelo, Motor motor, Tipocombustible tipocombustible, Tipovehiculo tipovehiculo, Version version_1, String descripcion, double precioLista, int stock, int kms) {
       this.color = color;
       this.condicion = condicion;
       this.marca = marca;
       this.modelo = modelo;
       this.motor = motor;
       this.tipocombustible = tipocombustible;
       this.tipovehiculo = tipovehiculo;
       this.version = version_1;
       this.descripcion = descripcion;
       this.precioLista = precioLista;
       this.stock = stock;
       this.kms = kms;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    public Color getColor() {
        return this.color;
    }
    
    public void setColor(Color color) {
        this.color = color;
    }
    public Condicion getCondicion() {
        return this.condicion;
    }
    
    public void setCondicion(Condicion condicion) {
        this.condicion = condicion;
    }
    public Marca getMarca() {
        return this.marca;
    }
    
    public void setMarca(Marca marca) {
        this.marca = marca;
    }
    public Modelo getModelo() {
        return this.modelo;
    }
    
    public void setModelo(Modelo modelo) {
        this.modelo = modelo;
    }
    public Motor getMotor() {
        return this.motor;
    }
    
    public void setMotor(Motor motor) {
        this.motor = motor;
    }
    public Tipocombustible getTipocombustible() {
        return this.tipocombustible;
    }
    
    public void setTipocombustible(Tipocombustible tipocombustible) {
        this.tipocombustible = tipocombustible;
    }
    public Tipovehiculo getTipovehiculo() {
        return this.tipovehiculo;
    }
    
    public void setTipovehiculo(Tipovehiculo tipovehiculo) {
        this.tipovehiculo = tipovehiculo;
    }
    public Version getVersion_1() {
        return this.version;
    }
    
    public void setVersion_1(Version version_1) {
        this.version = version_1;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public double getPrecioLista() {
        return this.precioLista;
    }
    
    public void setPrecioLista(double precioLista) {
        this.precioLista = precioLista;
    }
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }
    public int getKms() {
        return this.kms;
    }
    
    public void setKms(int kms) {
        this.kms = kms;
    }




}


