package Modelo;
// Generated 05/11/2019 00:34:25 by Hibernate Tools 4.3.1



import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Version generated by hbm2java
 */
@Entity
@Table (name="version")
public class Version  implements java.io.Serializable {

    @Id @GeneratedValue(strategy=javax.persistence.GenerationType.AUTO)
    private Long id;
    
    @OneToOne (targetEntity = Modelo.class, cascade= CascadeType.ALL,fetch=FetchType.LAZY)
    private Modelo modelo;
    private String nombre;
    private String observacion;

    public Version() {
    }

	
    public Version(Modelo modelo, String nombre, String observacion) {
        this.modelo = modelo;
        this.nombre = nombre;
        this.observacion = observacion;
    }
    public Version(Modelo modelo, String nombre, String observacion, Set vehiculos) {
       this.modelo = modelo;
       this.nombre = nombre;
       this.observacion = observacion;
       
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Modelo getModelo() {
        return this.modelo;
    }
    
    public void setModelo(Modelo modelo) {
        this.modelo = modelo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    
    @Override
    public String toString() {
        return nombre; //To change body of generated methods, choose Tools | Templates.
    }



}


