/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

//import static Gestor_Vista.GVistaMarcas.abrirVistaMarcas;

import Gestor_Vista.GV_Principal;
import static Gestor_Vista.GV_Principal.getInstancia;
import javax.swing.JFrame;



/**
 *
 * @author Germán
 */
public class FrmPrincipal extends javax.swing.JFrame {
    
    private static GV_Principal gestorVistaPrincipal;
    /**
     * Creates new form Principal
     */
    public FrmPrincipal() {
        configurarForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAdministración = new javax.swing.JMenu();
        menuMarca = new javax.swing.JMenuItem();
        menuModelo = new javax.swing.JMenuItem();
        menuColor = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuAdmVehiculos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Concesionaria GTM Multimarcas - Pantalla Principal");
        setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imagen_fondo_principal2.jpg"))); // NOI18N

        menuAdministración.setText("Administración");
        menuAdministración.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        menuMarca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        menuMarca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuMarca.setText("--Marcas--");
        menuMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMarcaActionPerformed(evt);
            }
        });
        menuAdministración.add(menuMarca);

        menuModelo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        menuModelo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuModelo.setText("--Modelos--");
        menuModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuModeloActionPerformed(evt);
            }
        });
        menuAdministración.add(menuModelo);

        menuColor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        menuColor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuColor.setText("--Colores--");
        menuColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuColorActionPerformed(evt);
            }
        });
        menuAdministración.add(menuColor);

        jMenuBar1.add(menuAdministración);

        jMenu1.setText("Vehiculos");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        menuAdmVehiculos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        menuAdmVehiculos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuAdmVehiculos.setText("--Administrar Vehiculos--");
        menuAdmVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAdmVehiculosActionPerformed(evt);
            }
        });
        jMenu1.add(menuAdmVehiculos);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuColorActionPerformed
        gestorVistaPrincipal.abrirMenuColor();
    }//GEN-LAST:event_menuColorActionPerformed

    private void menuMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMarcaActionPerformed
        gestorVistaPrincipal.abrirMenuMarca();
    }//GEN-LAST:event_menuMarcaActionPerformed

    private void menuAdmVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdmVehiculosActionPerformed
        gestorVistaPrincipal.abrirMenuAdmVehiculos();
    }//GEN-LAST:event_menuAdmVehiculosActionPerformed

    private void menuModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuModeloActionPerformed
        gestorVistaPrincipal.abrirMenuModelo();
    }//GEN-LAST:event_menuModeloActionPerformed
    
    private void configurarForm(){
        initComponents();
        gestorVistaPrincipal = getInstancia();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuAdmVehiculos;
    private javax.swing.JMenu menuAdministración;
    private javax.swing.JMenuItem menuColor;
    private javax.swing.JMenuItem menuMarca;
    private javax.swing.JMenuItem menuModelo;
    // End of variables declaration//GEN-END:variables
}
